import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Quarta entrega',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <header className="bg-gray-700 text-white">
        <div>
        <h2>MEUS PRODUTOS</h2>
        <ul>
          <li><Link href="/">HOME</Link></li>
          <li><Link href="/Produtos/tenis">Tênis</Link></li>
          <li><Link href="/Produtos/calca">Calça</Link></li>
          <li><Link href="/Produtos/camisa">Camisa</Link></li>
          <li><Link href="/Produtos/meia">Meia</Link></li>
        </ul>
      </div>
        </header>
        {children}</body>
    </html>
  )
}
